services:
  redis:
    image: redis:7-alpine
    container_name: api_ebusoft_redis
    restart: unless-stopped
    volumes:
      - ../redis_data:/data
    networks:
      - xyz

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_ebusoft
    depends_on:
      - redis
    expose:
      - "9999"
    networks:
      - xyz
    volumes:
      - ./tmp:/app/tmp
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_ebusoft_worker
    restart: unless-stopped
    depends_on:
      - redis
    command: >
      celery -A celery_conf.celery_app worker --loglevel=info -c 1
    volumes:
      - ./tmp:/app/tmp
      - ./logs:/app/logs
    env_file:
      - .env
    networks:
      - xyz

networks:
  xyz:
    external: true
